# Generated by Django 3.1.5 on 2021-01-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0002_auto_20210124_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='films_qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
